### ISSUE TITLE
Need to set TELEGRAM_TOKEN env variable error

### ISSUE THREAD

**Issue by vitaliypo** [dyrkin/luxmed-booking-service#5]
Hi.
I cloned this repo to newly created Oracle VM with ubuntu  (tried on desktop and server editions), installed java 10, docker, added to .bash_profile exports as stated in README (tried to add exports to other files related to loading bash sessions too).
When I try to run app with command from readme I see:
_Need to set TELEGRAM_TOKEN env variable_
Maybe I'm missing something in configuration?
![virtualbox_ubuntu server_04_07_2018_20_36_19](https://user-images.githubusercontent.com/23480475/42291355-76d4f89a-7fcb-11e8-9bd8-ffa1e7476864.png)

**Comment by dyrkin** [comment]
Hi,
Did you try to run the command without sudo? It looks like you are trying to set env variable for current user but running the app from super user, which doesn’t have this variable configured

**Comment by vitaliypo** [comment]
Indeed, when trying to run under my user, I see other errors. Probably should install and configure all the software like docker properly.
Thank you.

**Comment by dyrkin** [comment]
It might be easier to use the second option
1) install postgres and create db **lbs** with login **lbs** and password **lsb123**
2) run using `./gradlew bootRun`
